//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EventsoEntities : DbContext
    {
        public EventsoEntities()
            : base("name=EventsoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<State> States { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<District> Districts { get; set; }
        public virtual DbSet<Vendor> Vendors { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<Testimonial> Testimonials { get; set; }
        public virtual DbSet<VendorCategory> VendorCategories { get; set; }
        public virtual DbSet<Viewership> Viewerships { get; set; }
        public virtual DbSet<OfficeAddress> OfficeAddresses { get; set; }
        public virtual DbSet<CategoryFilter> CategoryFilters { get; set; }
    }
}
