//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Viewership
    {
        public int ViewershipId { get; set; }
        public Nullable<int> VendorId { get; set; }
        public Nullable<System.DateTime> ViewDate { get; set; }
        public Nullable<int> ViewedBy { get; set; }
        public Nullable<bool> HasSentMail { get; set; }
        public Nullable<bool> HasSentSMS { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual User CreatedUser { get; set; }
        public virtual User UpdatedUser { get; set; }
        public virtual User ViewedUser { get; set; }
        public virtual Vendor Vendor { get; set; }
    }
}
